<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<script>
    let p = new Promise(function(res,rej){
       /*  setTimeout(()=>{
            console.log(qqq)
        },2000) */
       /*  $.ajax({
            url:'./1.json',
            success:function(data){
                res(data)
            },
            error:function(err){
                rej(err)
            }
        }) */
        res(qqq)
        res(222)
    }).then(function(data){
        console.log(1);
        console.log(data)
    },function(error){
        console.log(0)
    }).catch((err)=>{
        console.log(666,err)
    }).finally(()=>{
        //不管是 成功还是失败 都要执行的代码  我们可以放到这个函数中；
    })
    //一个错误信息只捕获一次
    //第二个then是上一个then执行的返回结果
    //then catch finally 这三个方法是在Promise的原型上；
    //all race resolve reject

    var p1 = new Promise(function(res,rej){
        setTimeout(()=>{
            res(1111)
            console.log(1)
        },2000);
    });
    var p2 = new Promise(function(res,rej){
        setTimeout(()=>{
            rej(2222)
            console.log(2)
        },3000);
    });
    var p3 = new Promise(function(res,rej){
        setTimeout(()=>{
            res(3333)
            console.log(3)
        },4000);
    });
    //所有的都成功 才会走成功的回调函数 只要有一个失败 就会直接走对应的失败函数
    //executor函数是一个同步执行的函数，then catch里边的函数是异步执行的；
    Promise.all([p1,p2,p3]).then((data)=>{
        console.log('data',data)
    },(err)=>{
        console.log('err',err)
    });
    Promise.allSettled([p1,p2,p2]).then((data)=>{
        console.log(data)
    });

    Promise.race([p1,p2,p3]).then((data)=>{
        console.log('success',data)
    },(err)=>{
        console.log('fail',err)
    });

    Promise.resolve(333).then((data)=>{
        console.log(data)
    });

    Promise.reject(444).then((data)=>{
        console.log(data)
    }).catch((err)=>{
        console.log(err)
    });
</script>